apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: podx
    spec:
      containers:
        - name: podx
          image: mdymen85/kubernetes-test:1.0
  selector:
    matchLabels:
      app: podx
          
